"""
validation/email_sender.py
===========================
Sends the HTML report via AWS SES.

Config section (in audit_analysis_config.json → reporting):
    "reporting": {
        "email": {
            "enabled": true,
            "from_address": "dq-alerts@example.com",
            "to_addresses": ["team@example.com", "manager@example.com"],
            "cc_addresses": [],
            "subject_prefix": "[Strands DQ]",
            "attach_csvs": false
        }
    }

Requires SES to be set up in the configured AWS region with the from_address
verified (or the domain verified in production SES).

Falls back gracefully — if SES fails or email is disabled, just logs a warning
and writes the HTML to disk.
"""

from __future__ import annotations

import base64
import logging
import mimetypes
from pathlib import Path
from typing import Any, Dict, List, Optional

import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)


class EmailSender:
    """
    Sends an HTML report email via AWS SES.

    Parameters
    ----------
    email_cfg : dict
        The reporting.email block from config.
    aws_region : str
        AWS region where SES is configured.
    """

    def __init__(self, email_cfg: Dict[str, Any], aws_region: str = "us-east-1"):
        self.cfg    = email_cfg
        self.ses    = boto3.client("ses", region_name=aws_region)
        self.enabled = email_cfg.get("enabled", False)

    def send(
        self,
        html_body: str,
        run_date: str,
        attachment_paths: Optional[List[str]] = None,
    ) -> bool:
        """
        Send the HTML report email.

        Parameters
        ----------
        html_body : str
            Full HTML string to send as the message body.
        run_date : str
            YYYY-MM-DD — used in the subject line.
        attachment_paths : list of str, optional
            Paths to CSV files to attach (used only if attach_csvs=true in config).

        Returns True on success, False on failure.
        """
        if not self.enabled:
            logger.info("[EmailSender] Email disabled in config — skipping.")
            return False

        to_addrs  = self.cfg.get("to_addresses", [])
        cc_addrs  = self.cfg.get("cc_addresses", [])
        from_addr = self.cfg.get("from_address", "")
        prefix    = self.cfg.get("subject_prefix", "[Strands DQ]")
        subject   = f"{prefix} Data Quality Report — {run_date}"
        attach    = self.cfg.get("attach_csvs", False)

        if not to_addrs or not from_addr:
            logger.warning("[EmailSender] to_addresses or from_address missing in config.")
            return False

        # Build a plain-text fallback
        plain_text = (
            f"Strands AI Data Quality Report for {run_date}\n\n"
            "Please view this email in an HTML-capable client.\n\n"
            "Report generated by Strands Audit Analysis Pipeline."
        )

        if attach and attachment_paths:
            return self._send_with_attachments(
                subject, from_addr, to_addrs, cc_addrs,
                html_body, plain_text, attachment_paths,
            )
        else:
            return self._send_simple(
                subject, from_addr, to_addrs, cc_addrs, html_body, plain_text
            )

    # ------------------------------------------------------------------
    # Simple send (no attachments — uses SES send_email API)
    # ------------------------------------------------------------------

    def _send_simple(
        self,
        subject: str,
        from_addr: str,
        to_addrs: List[str],
        cc_addrs: List[str],
        html_body: str,
        plain_text: str,
    ) -> bool:
        try:
            dest: Dict[str, Any] = {"ToAddresses": to_addrs}
            if cc_addrs:
                dest["CcAddresses"] = cc_addrs

            self.ses.send_email(
                Source=from_addr,
                Destination=dest,
                Message={
                    "Subject": {"Data": subject, "Charset": "UTF-8"},
                    "Body": {
                        "Text": {"Data": plain_text, "Charset": "UTF-8"},
                        "Html": {"Data": html_body,  "Charset": "UTF-8"},
                    },
                },
            )
            logger.info(
                f"[EmailSender] Report sent to {to_addrs} (subject: {subject})"
            )
            return True
        except ClientError as e:
            logger.error(f"[EmailSender] SES send_email failed: {e}")
            return False

    # ------------------------------------------------------------------
    # Send with CSV attachments (uses SES send_raw_email + MIME)
    # ------------------------------------------------------------------

    def _send_with_attachments(
        self,
        subject: str,
        from_addr: str,
        to_addrs: List[str],
        cc_addrs: List[str],
        html_body: str,
        plain_text: str,
        attachment_paths: List[str],
    ) -> bool:
        import email.mime.multipart as mp
        import email.mime.text      as mt
        import email.mime.base      as mb
        import email.encoders       as enc

        msg = mp.MIMEMultipart("mixed")
        msg["Subject"] = subject
        msg["From"]    = from_addr
        msg["To"]      = ", ".join(to_addrs)
        if cc_addrs:
            msg["Cc"] = ", ".join(cc_addrs)

        # Body: alternative (text + html)
        alt = mp.MIMEMultipart("alternative")
        alt.attach(mt.MIMEText(plain_text, "plain", "utf-8"))
        alt.attach(mt.MIMEText(html_body,  "html",  "utf-8"))
        msg.attach(alt)

        # Attachments
        for path_str in attachment_paths:
            p = Path(path_str)
            if not p.exists():
                continue
            mime_type, _ = mimetypes.guess_type(str(p))
            main_type, sub_type = (mime_type or "application/octet-stream").split("/", 1)
            with open(p, "rb") as fh:
                data = fh.read()
            part = mb.MIMEBase(main_type, sub_type)
            part.set_payload(data)
            enc.encode_base64(part)
            part.add_header("Content-Disposition", "attachment", filename=p.name)
            msg.attach(part)

        try:
            all_addrs = to_addrs + cc_addrs
            self.ses.send_raw_email(
                Source=from_addr,
                Destinations=all_addrs,
                RawMessage={"Data": msg.as_bytes()},
            )
            logger.info(
                f"[EmailSender] Report + {len(attachment_paths)} attachment(s) "
                f"sent to {to_addrs}"
            )
            return True
        except ClientError as e:
            logger.error(f"[EmailSender] SES send_raw_email failed: {e}")
            return False
