"""
validation/email_sender.py
===========================
Sends the HTML report via SMTP (standard Python smtplib — no AWS dependency).

Config section (in audit_analysis_config.json → reporting.email):

    "reporting": {
        "email": {
            "enabled": true,
            "smtp_host": "smtp.gmail.com",
            "smtp_port": 587,
            "sender": "dq-alerts@example.com",
            "recipients": ["team@example.com", "manager@example.com"],
            "cc": ["governance@example.com"],
            "subject": "[Strands DQ] Data Quality Report",
            "username": "dq-alerts@example.com",
            "password": "app-password-here",
            "use_tls": true,
            "attach_csvs": false
        }
    }

Authentication is optional — omit username/password for relay servers
that do not require credentials.

TLS behaviour:
  use_tls=true  + port 587  → STARTTLS (most common — Gmail, Outlook, Office 365)
  use_tls=true  + port 465  → SMTP_SSL
  use_tls=false             → plain SMTP (internal relay, localhost)
"""

from __future__ import annotations

import logging
import mimetypes
import smtplib
import ssl
import email.mime.multipart as mp
import email.mime.text      as mt
import email.mime.base      as mb
import email.encoders       as enc
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class EmailSender:
    """
    Sends an HTML report email via SMTP.

    Parameters
    ----------
    email_cfg : dict
        The reporting.email block from config.
    """

    def __init__(self, email_cfg: Dict[str, Any], **_kwargs):
        self.cfg     = email_cfg
        self.enabled = email_cfg.get("enabled", False)

    def send(
        self,
        html_body: str,
        run_date: str,
        attachment_paths: Optional[List[str]] = None,
    ) -> bool:
        """
        Send the HTML report email via SMTP.

        Parameters
        ----------
        html_body : str
            Full HTML string to send as the message body.
        run_date : str
            YYYY-MM-DD — appended to the subject line if not already present.
        attachment_paths : list of str, optional
            CSV files to attach (used only when attach_csvs=true in config).

        Returns True on success, False on failure.
        """
        if not self.enabled:
            logger.info("[EmailSender] Email disabled in config — skipping.")
            return False

        smtp_host  = self.cfg.get("smtp_host", "localhost")
        smtp_port  = int(self.cfg.get("smtp_port", 587))
        sender     = self.cfg.get("sender", "")
        recipients = self.cfg.get("recipients", [])
        cc         = self.cfg.get("cc", [])
        subject    = self.cfg.get("subject", "[Strands DQ] Data Quality Report")
        username   = self.cfg.get("username", "")
        password   = self.cfg.get("password", "")
        use_tls    = self.cfg.get("use_tls", True)
        attach     = self.cfg.get("attach_csvs", False)

        if not recipients or not sender:
            logger.warning("[EmailSender] 'sender' or 'recipients' missing in config.")
            return False

        # Append run_date to subject if not already included
        if run_date not in subject:
            subject = f"{subject} — {run_date}"

        all_to = recipients + cc
        plain_text = (
            f"Strands AI Data Quality Report for {run_date}\n\n"
            "Please view this email in an HTML-capable client.\n\n"
            "Report generated by Strands Audit Analysis Pipeline."
        )

        # Build the MIME message
        msg = mp.MIMEMultipart("mixed")
        msg["Subject"] = subject
        msg["From"]    = sender
        msg["To"]      = ", ".join(recipients)
        if cc:
            msg["Cc"]  = ", ".join(cc)

        # Alternative body: plain text + HTML
        alt = mp.MIMEMultipart("alternative")
        alt.attach(mt.MIMEText(plain_text, "plain", "utf-8"))
        alt.attach(mt.MIMEText(html_body,  "html",  "utf-8"))
        msg.attach(alt)

        # Optional CSV attachments
        if attach and attachment_paths:
            for path_str in attachment_paths:
                p = Path(path_str)
                if not p.exists():
                    logger.warning(f"[EmailSender] Attachment not found, skipping: {p}")
                    continue
                mime_type, _ = mimetypes.guess_type(str(p))
                main_type, sub_type = (mime_type or "application/octet-stream").split("/", 1)
                with open(p, "rb") as fh:
                    data = fh.read()
                part = mb.MIMEBase(main_type, sub_type)
                part.set_payload(data)
                enc.encode_base64(part)
                part.add_header("Content-Disposition", "attachment", filename=p.name)
                msg.attach(part)
            logger.debug(f"[EmailSender] Attached {len(attachment_paths)} file(s)")

        # Send
        try:
            if use_tls and smtp_port == 465:
                # SSL from the start
                context = ssl.create_default_context()
                with smtplib.SMTP_SSL(smtp_host, smtp_port, context=context) as server:
                    if username and password:
                        server.login(username, password)
                    server.sendmail(sender, all_to, msg.as_bytes())
            elif use_tls:
                # STARTTLS (port 587 or custom)
                context = ssl.create_default_context()
                with smtplib.SMTP(smtp_host, smtp_port) as server:
                    server.ehlo()
                    server.starttls(context=context)
                    server.ehlo()
                    if username and password:
                        server.login(username, password)
                    server.sendmail(sender, all_to, msg.as_bytes())
            else:
                # Plain SMTP — internal relay / localhost
                with smtplib.SMTP(smtp_host, smtp_port) as server:
                    if username and password:
                        server.login(username, password)
                    server.sendmail(sender, all_to, msg.as_bytes())

            logger.info(
                f"[EmailSender] Report sent via {smtp_host}:{smtp_port} "
                f"→ {recipients} (subject: {subject})"
            )
            return True

        except smtplib.SMTPAuthenticationError as e:
            logger.error(f"[EmailSender] SMTP authentication failed: {e}")
        except smtplib.SMTPConnectError as e:
            logger.error(f"[EmailSender] Could not connect to {smtp_host}:{smtp_port} — {e}")
        except smtplib.SMTPException as e:
            logger.error(f"[EmailSender] SMTP error: {e}")
        except OSError as e:
            logger.error(f"[EmailSender] Network error: {e}")
        return False
