# ═══════════════════════════════════════════════════════════════════
# ANNOTATED SCRIPT  — generated by Cost Optimizer
# Original : pyscript/customer_order_summary_glue.py
# Generated: 2026-05-05 18:28 UTC
# ═══════════════════════════════════════════════════════════════════

# ╔═══════════════════════════════════════════════════════════════════╗
# ║          COST OPTIMIZER — RECOMMENDATIONS SUMMARY                ║
# ╚═══════════════════════════════════════════════════════════════════╝
#
# [!!] ── P0  CRITICAL — fix before next run
#      • JVM heap critical — upgrade memory or worker type [glue_metrics]
#        Heap p90=98%, max=98%. OOM risk detected from Glue CloudWatch metrics.
#        ↳ Upgrade worker type G.2X → G.4X; add spark.executor.memoryOverhead; enable G1GC.
#
# [! ] ── P1  HIGH     — fix this sprint
#      • Driver CPU overloaded (86% avg) [glue_metrics]
#        Driver is doing heavy work — likely .collect(), .toPandas(), or complex DAG pl
#        anning.
#        ↳ Replace .collect() with .write(); avoid toPandas() on large DataFrames; use broadcast joins instead 
#      • Workers over-provisioned — reduce from 20 → 9 [glue_metrics]
#        Only 8.8 of 20 workers active on average (44% utilisation). Idle workers bille
#        d but doing no work.
#        ↳ Set number_of_workers=9; enable spark.dynamicAllocation.
#      • Stage velocity slow — possible data skew or shuffle bottleneck [glue_metrics]
#        Only ? stages completed. Job likely stalled on one large task per stage.
#        ↳ Enable AQE skewJoin; add salting to join keys with high cardinality; check shuffle read/write sizes 
#      • Apply 11 metric-derived Spark config(s) [glue_metrics]
#        Spark configs tuned from actual Glue CloudWatch runtime data.
#        ↳   spark.executor.memory = 12g
#
# ── Inline comments below mark every flagged line in the code. ──────
# ── Full cost table and Spark configs are at the bottom of this file. 
# ════════════════════════════════════════════════════════════════════

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from pyspark.sql.functions import *
from pyspark.sql.window import Window
from datetime import datetime
from awsglue.dynamicframe import DynamicFrame

# Initialize Glue context
args = getResolvedOptions(sys.argv, ['JOB_NAME'])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

# Define databases
source_db = "ecommerce_db"
target_db = "analytics_db"

# Step 1: Read source tables from Glue Catalog
print("Reading source tables from Glue Catalog...")

# Read customers table
customers_df = glueContext.create_dynamic_frame.from_catalog(
    database=source_db,
    table_name="customers",
    transformation_ctx="customers_df"
).toDF()

# Read orders table
orders_df = glueContext.create_dynamic_frame.from_catalog(
    database=source_db,
    table_name="orders",
    transformation_ctx="orders_df"
).toDF()

# Read products table
products_df = glueContext.create_dynamic_frame.from_catalog(
    database=source_db,
    table_name="products",
    transformation_ctx="products_df"
).toDF()

print(f"Customers: {customers_df.count()} records")
print(f"Orders: {orders_df.count()} records")
print(f"Products: {products_df.count()} records")

# Step 2: Apply filters as per config
print("Applying data filters...")
customers_df.printSchema()
customers_filtered = customers_df.filter(col("active.boolean") == True)

orders_filtered = orders_df.filter(
    (col("status") == "completed") &
    (col("order_date") >= "2023-01-01")
)

products_filtered = products_df.filter(col("active.boolean") == True)

# Step 3: Perform joins
print("Performing table joins...")

# Join customers with orders
customer_orders = customers_filtered.join(
    orders_filtered,
    customers_filtered.customer_id == orders_filtered.customer_id,
    "inner"
).select(
    customers_filtered.customer_id,
    customers_filtered.name.alias("customer_name"),
    customers_filtered.email,
    customers_filtered.region,
    customers_filtered.signup_date,
    orders_filtered.order_id,
    orders_filtered.product_id,
    orders_filtered.order_date,
    orders_filtered.quantity,
    orders_filtered.total_amount,
    orders_filtered.status
)

# Join with products
full_orders = customer_orders.join(
    products_filtered,
    customer_orders.product_id == products_filtered.product_id,
    "left"
).select(
    customer_orders.customer_id,
    customer_orders.customer_name,
    customer_orders.region,
    customer_orders.order_id,
    customer_orders.product_id,
    customer_orders.order_date,
    customer_orders.quantity,
    customer_orders.total_amount,
    products_filtered.product_name,
    products_filtered.category,
    products_filtered.price,
    products_filtered.cost
)

# Step 4: Calculate derived columns
print("Calculating derived columns...")
full_orders.printSchema()

# Calculate profit margin
full_orders = full_orders.withColumn(
    "profit_margin_pct",
    ((col("price.decimal") - col("cost.decimal")) / col("price.decimal")) * 100
)

# Step 5: Perform aggregations
print("Performing customer-level aggregations...")

customer_summary = full_orders.groupBy(
    col("customer_id.int").alias("customer_id"),
    "customer_name",
    "region"
).agg(
    count("order_id.int").alias("total_orders"),
    sum("quantity.int").alias("total_quantity"),
    sum("total_amount.decimal").alias("total_revenue"),
    avg("total_amount.decimal").alias("avg_order_value"),
    max("order_date").alias("last_order_date"),
    avg("profit_margin_pct").alias("avg_profit_margin")
)

# Step 6: Calculate customer lifetime value
customer_summary = customer_summary.withColumn(
    "customer_lifetime_value",
    col("total_revenue") * (1 + col("avg_profit_margin") / 100)
)

# Step 7: Find top category per customer
print("Finding top category per customer...")

# First, get category counts per customer
category_counts = full_orders.groupBy(
    col("customer_id.int").alias("customer_id"), "category"
).agg(
    count("*").alias("category_count")
)

# Use window function to rank categories
window_spec = Window.partitionBy("customer_id").orderBy(desc("category_count"))

category_ranked = category_counts.withColumn(
    "rank",
    row_number().over(window_spec)
)

# Get top category for each customer
top_categories = category_ranked.filter(col("rank") == 1).select(
    "customer_id",
    "category"
)

# Join back to customer summary
customer_summary = customer_summary.join(
    top_categories,
    "customer_id",
    "left"
).withColumnRenamed("category", "top_category")

# Step 8: Add processing timestamp
customer_summary = customer_summary.withColumn(
    "processed_at",
    current_timestamp()
)

# Step 9: Write to target table
print("Writing results to target table...")

# Convert back to DynamicFrame for Glue catalog operations
output_dynamic_frame = DynamicFrame.fromDF(
    customer_summary,
    glueContext,
    "output_dynamic_frame"
)

S3_OUTPUT_PATH = "s3://strands-etl-data/ecommerce/target1/"
OUTPUT_FORMAT = "parquet"
# Write to Glue catalog table
# glueContext.write_dynamic_frame.from_catalog(
#     frame=output_dynamic_frame,
#     database=target_db,
#     table_name="customer_order_summary",
#     transformation_ctx="output_dynamic_frame"
# )

glueContext.write_dynamic_frame.from_options(
    frame=output_dynamic_frame,
    connection_type="s3",  # Tells Glue the sink is S3
    connection_options={
        "path": S3_OUTPUT_PATH,
        
        # --- KEY SETTINGS TO CREATE THE TABLE ---
        "enableUpdateCatalog": True,  # This flag enables catalog interaction
        "database": target_db,
        "table": "customer_order_summary"
    },
    format=OUTPUT_FORMAT, # Specifies the file format
    transformation_ctx="output_dynamic_frame"
)

print("ETL job completed successfully!")
print(f"Processed {customer_summary.count()} customer records")

job.commit()

# ══════════════════════════════════════════════════════════════════════
#   COST OPTIMIZER REPORT
# ══════════════════════════════════════════════════════════════════════
# 
#   COST SUMMARY
#   Metric                                                  Value
#   ──────────────────────────────────────────────────────────────
#   Current cost / run                                    $1.8300
#   Optimal cost / run                                    $0.0500
#   Potential savings                                         80%
#   Potential annual savings                                 $535
#   Effective data size                                    3.3 GB
#   Anti-patterns found                                         0
#   Critical issues                                             0
# 
#   MULTI-PLATFORM COST COMPARISON
#   Platform                                         Cost/run   Monthly (20×)
#   ──────────────────────────────────────────────────────────────────────────
#   AWS Athena (Trino/Presto)                         $0.0033           $0.07
#   AWS Lambda (simple ETL)                           $0.0210           $0.42
#   GCP Dataproc Serverless                           $0.0277           $0.55
#   AWS EKS + Karpenter (Spot)                        $0.0725           $1.45
#   AWS EMR (Spot m5.2xl)                             $0.0869           $1.74
#   GCP Dataproc (Spot n2-standard-8)                 $0.0913           $1.83
#   Databricks on AWS (Spot)                          $0.1113           $2.23
#   Azure HDInsight (D4s_v3)                          $0.1210           $2.42
#   AWS EMR Serverless (Spark)                        $0.1257           $2.51
#   Azure Synapse Spark                               $0.2016           $4.03
#   Databricks on Azure (Jobs Compute)                $0.2150           $4.30
#   Databricks on AWS (Jobs Compute)                  $0.2243           $4.49
#   AWS Glue G.1X                                     $0.2772           $5.54
#   AWS EMR (On-Demand m5.2xl)                        $0.2904           $5.81
#   GCP Dataproc (n2-standard-8)                      $0.3055           $6.11
#   AWS Glue G.2X                                     $0.5544          $11.09
# 
#   RECOMMENDATIONS (by priority)
#   ──────────────────────────────────────────────────────────────
#   [P0]
#     • JVM heap critical — upgrade memory or worker type
#       Heap p90=98%, max=98%. OOM risk detected from Glue CloudWatch metrics.
#       Implementation: Upgrade worker type G.2X → G.4X; add spark.executor.memoryOverhead; enable G1GC.
#       Impact: Prevents OOM crashes; reduces retry cost
# 
#   [P1]
#     • Driver CPU overloaded (86% avg)
#       Driver is doing heavy work — likely .collect(), .toPandas(), or complex DAG plan
#       ning.
#       Implementation: Replace .collect() with .write(); avoid toPandas() on large DataFrames; use broadcast joins instead 
#       Impact: Reduces driver bottleneck and OOM risk
#     • Workers over-provisioned — reduce from 20 → 9
#       Only 8.8 of 20 workers active on average (44% utilisation). Idle workers billed 
#       but doing no work.
#       Implementation: Set number_of_workers=9; enable spark.dynamicAllocation.
#       Impact: ~56% worker cost reduction
#     • Stage velocity slow — possible data skew or shuffle bottleneck
#       Only ? stages completed. Job likely stalled on one large task per stage.
#       Implementation: Enable AQE skewJoin; add salting to join keys with high cardinality; check shuffle read/write sizes 
#       Impact: Can reduce job duration by 30-70% for skewed workloads
#     • Apply 11 metric-derived Spark config(s)
#       Spark configs tuned from actual Glue CloudWatch runtime data.
#       Implementation:   spark.executor.memory = 12g
  spark.executor.memoryOverhead = 3g
  spark.memory.fraction = 0.80
  
#       Impact: Right-sizes memory, CPU, and parallelism to actual workload
# 
#   GLUE RUNTIME METRICS ANALYSIS
#   ──────────────────────────────────────────────────────────────
#     CRITICAL: JVM heap peaked at 98% – OOM risk. Increase executor memory or upgrade
#      worker type immediately.
#     Driver CPU overloaded (86% avg). Increase driver memory/cores or reduce collect(
#     )/toPandas() calls on driver.
#     Workers under-utilised: avg 8.8 / 24 allocated (37%). Reduce number_of_workers b
#     y ~63%.
#     Only 10 stages completed – job may have wide shuffle dependencies or be stuck. C
#     heck for data skew.
# 
#   WORKER SIZING RECOMMENDATION
#     Current : 20 × G.2X
#     Optimal : 9 × G.4X
#     Reason  : Workers under-utilised (avg 8.8/20)
#     Reason  : High JVM heap → upgrade worker type G.2X→G.4X
# 
#   METRIC-DERIVED SPARK CONFIGS (add to SparkSession)
#   ──────────────────────────────────────────────────────────────
#     .config("spark.executor.memory", "12g")
#     .config("spark.executor.memoryOverhead", "3g")
#     .config("spark.memory.fraction", "0.80")
#     .config("spark.memory.storageFraction", "0.25")
#     .config("spark.rdd.compress", "true")
#     .config("spark.shuffle.compress", "true")
#     .config("spark.shuffle.spill.compress", "true")
#     .config("spark.dynamicAllocation.enabled", "true")
#     .config("spark.dynamicAllocation.shuffleTracking.enabled", "true")
#     .config("spark.dynamicAllocation.maxExecutors", "8")
#     .config("spark.dynamicAllocation.minExecutors", "4")
# 
# ══════════════════════════════════════════════════════════════════════
